[package]
name = "htsget"
version = "0.1.0"
edition = "2018"

# XXX: interferes with lambdas?
# [[bin]]
# name = "hstget"
# doc = false

[dependencies]
lambda_runtime = "0.2.1"
lambda_http = "0.1.1"
serde_json = "1.0.40"
env_logger = "0.6.2"
clap = "2.33.0"
dotenv_codegen = "0.14.1"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
#futures = { version = "0.1.28" }
futures-preview = { version = "=0.3.0-alpha.17", features = ["compat", "async-await", "nightly"] }
tokio-core = { version = "0.1.17" }

# https://www.rusoto.org/lambdas.html
# """
# The rustls option must be set on the project's Cargo.toml 
# file for both the rusoto_core crate and any Rusoto service 
# crates used" "rustls" is required for all lambdas
# """
rusoto_athena = {version = "0.40.0", default_features = false, features=["rustls"]}
rusoto_core = {version = "0.40.0", default_features = false, features=["rustls"]}
