[package]
name = "htsget"
version = "0.1.0"
edition = "2018"

[dependencies]
lambda_runtime = "0.2.1"
lambda_http = "0.1.1"
serde_json = "1.0.39"
env_logger = "0.6.1"
clap = "2.33.0"
dotenv_codegen = "0.14.1"
uuid = { version = "0.7.4", features = ["serde", "v4"] }

# https://www.rusoto.org/lambdas.html
# """
# The rustls option must be set on the project's Cargo.toml 
# file for both the rusoto_core crate and any Rusoto service 
# crates used" "rustls" is required for all lambdas
# """
rusoto_athena = {version = "0.40.0", default_features = false, features=["rustls"]}
rusoto_core = {version = "0.40.0", default_features = false, features=["rustls"]}
