Resources:
  htsgetAws:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: htsget-aws
      Handler: bootstrap
      Runtime: provided
      MemorySize: 128
      CodeUri: .
    Metadata:
      BuildMethod: makefile
