[package]
name = "htsget-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
# Just barebones clap, no coloring, etc...
clap = { default-features = false, version = "2.33.3"}
httpmock = "0.5.0"
#reqwest = { version = "0.10", features = ["json"] }
isahc = "0.9.10"

[[bin]]
name = "reads"
path = "aws/src/reads/main.rs"

#[[bin]]
#name = "variants"
#path = "aws/src/variants/main.rs"