[package]
name = "client"
version = "0.1.0"
edition = "2018"
default-run = "htsget"

[dependencies]
# Just barebones clap, no coloring, etc...
clap = { default-features = false, version = "2.33.0"}

[[bin]]
name = "htsget"
path = "main.rs"
