[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dev-dependencies]
httpmock = "0.5.0"
reqwest = { version = "0.10", features = ["json"] }
isahc = "0.9.10"

[[bin]]
name = "server"
path = "main.rs"
